apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  labels:
    app: landing-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      serviceAccountName: landing-page
      containers:
      - name: landing-page
        image: nginx:latest
        ports:
        - name: landing-page
          containerPort: 80
        resources:
          requests:
            memory: "8Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: landing-page
  name: landing-page
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: landing-page
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: landing-page
